import { Map,Marker,Annotation,MapPolyline,MapCompass,useObservable,useState,useEffect,VStack,HStack,Text,Image,ScrollView,Spacer,Button } from "scripting"
import { Coordinate,Stop,Vehicle,Alert,Line } from "./types"
import { LineBadge,Empty } from "./common"
import { realtime } from "../scripts/lib/kavnav"
import { normalizeVehicles } from "../scripts/lib/normalize"
import { updateRenderSelection } from "../scripts/lib/context"
import { InlineLoadingIndicator } from "./loading-view"
const H={map:"\u05de\u05e4\u05d4",live:"\u05e8\u05db\u05d1\u05d9\u05dd",stops:"\u05ea\u05d7\u05e0\u05d5\u05ea",alerts:"\u05d4\u05ea\u05e8\u05d0\u05d5\u05ea",refresh:"\u05e8\u05e2\u05e0\u05df",refreshing:"\u05de\u05e8\u05e2\u05e0\u05df...",none:"\u05d0\u05d9\u05df \u05e8\u05db\u05d1\u05d9\u05dd \u05de\u05d3\u05d5\u05d5\u05d7\u05d9\u05dd \u05db\u05e8\u05d2\u05e2",noAlerts:"\u05d0\u05d9\u05df \u05d4\u05ea\u05e8\u05d0\u05d5\u05ea \u05e4\u05e2\u05d9\u05dc\u05d5\u05ea",direction:"\u05db\u05d9\u05d5\u05d5\u05df",variant:"\u05d7\u05dc\u05d5\u05e4\u05d4",vehicles:"\u05e8\u05db\u05d1\u05d9\u05dd \u05d7\u05d9\u05d9\u05dd",next:"\u05d4\u05ea\u05d7\u05e0\u05d4 \u05d4\u05d1\u05d0\u05d4"}
export default function LineView({line,stops=[],coordinates=[],vehicles=[],alerts=[],height=245,liveOnly=false,lastVehicleReport}:{line:Line;stops?:Stop[];coordinates?:Coordinate[];vehicles:Vehicle[];alerts?:Alert[];height?:number;liveOnly?:boolean;lastVehicleReport?:string}){
  const [selected,setSelected]=useState<string|undefined>(undefined),[tab,setTab]=useState(liveOnly?"live":"map"),[live,setLive]=useState(vehicles),[updated,setUpdated]=useState(lastVehicleReport),[refreshing,setRefreshing]=useState(false)
  const allCoords=[...coordinates,...live.map(v=>v.coordinate).filter(Boolean) as Coordinate[],...stops.map(s=>s.coordinate).filter(Boolean) as Coordinate[]]
  const region=MapUtils.regionFromCoordinates(allCoords.length?allCoords:[{latitude:31.78,longitude:35.22}],0.22)||{center:{latitude:31.78,longitude:35.22},span:{latitudeDelta:.05,longitudeDelta:.05}}
  const camera=useObservable(MapCameraPosition.region(region)),number=String(line.lineNumber||line.routeNumber||""),routeCode=String(line.routeCode||line.code||""),routeId=String(line.routeId||"")
  const focusVehicle=(v:Vehicle)=>{setSelected(v.vehicleId);if(v.coordinate)camera.setValue(MapCameraPosition.region({center:v.coordinate,span:{latitudeDelta:.012,longitudeDelta:.012}}))}
  const focusStop=(s:Stop)=>{if(s.coordinate)camera.setValue(MapCameraPosition.region({center:s.coordinate,span:{latitudeDelta:.012,longitudeDelta:.012}}))}
  const refresh=async()=>{if(!routeCode||refreshing)return;setRefreshing(true);try{const raw=await realtime({routeCode});setLive(normalizeVehicles(raw).filter(v=>!routeId||v.routeId===routeId));setUpdated(raw?.lastVehicleReport)}finally{setRefreshing(false)}}
  useEffect(()=>{updateRenderSelection({selectedRoute:{lineNumber:number,routeId,routeCode,direction:line.direction,alternative:line.alternative,agency:line.agency,headsign:line.headsign}});if(!routeCode)return;let cancelled=false,timer:any;const tick=async()=>{try{const raw=await realtime({routeCode});if(cancelled)return;setLive(normalizeVehicles(raw).filter(v=>!routeId||v.routeId===routeId));setUpdated(raw?.lastVehicleReport)}catch{}if(!cancelled)timer=setTimeout(tick,15000)};timer=setTimeout(tick,15000);return()=>{cancelled=true;if(timer)clearTimeout(timer)}},[])
  return <VStack spacing={0}>
    <HStack padding={{horizontal:14,top:10,bottom:6}}><LineBadge line={number||"?"} color={line.color}/><VStack alignment="trailing" spacing={1}><Text font="headline" fontWeight="bold" lineLimit={1}>{line.headsign||line.routeLongName||line.longName||`Line ${number}`}</Text><Text font="caption" foregroundStyle="secondaryLabel">{H.direction} {line.direction||"?"}{line.alternative?` \u00b7 ${H.variant} ${line.alternative}`:""}{updated?` \u00b7 ${live.length} ${H.vehicles}`:""}</Text></VStack><Spacer/>{refreshing?<InlineLoadingIndicator kind="line" text="מעדכן רכבים חיים"/>:null}{routeCode?<Button title={refreshing?H.refreshing:H.refresh} action={()=>{void refresh()}} buttonStyle="bordered" controlSize="small"/>:null}</HStack>
    <ScrollView axes="horizontal" padding={{horizontal:12,bottom:6}}><HStack spacing={6}>{[["map",H.map],["live",H.live],["stops",H.stops],["alerts",H.alerts]].map(([id,t])=><Button key={id} title={t} action={()=>setTab(id)} buttonStyle={tab===id?"borderedProminent":"bordered"} controlSize="small"/>)}</HStack></ScrollView>
    {tab==="map"||tab==="live"?<Map cameraPosition={camera} frame={{height}} mapStyle={{style:"standard"}} clipShape={{type:"rect",cornerRadius:14}} controls={<MapCompass/>}>{coordinates.length>1?<MapPolyline coordinates={coordinates} strokeColor={line.color||"systemBlue"} strokeStyle={{lineWidth:5,lineCap:"round",lineJoin:"round"}}/>:null}{stops.filter((_,i)=>i===0||i===stops.length-1||i%Math.max(1,Math.ceil(stops.length/18))===0).map(s=>s.coordinate?<Marker key={s.code} coordinate={s.coordinate} title={s.name} tint="secondaryLabel" systemImage="circle.fill"/>:null)}{live.map(v=>v.coordinate?<Annotation key={v.vehicleId} coordinate={v.coordinate} title={`Line ${v.lineNumber||number}`} anchor="center"><VStack frame={{minWidth:34,height:28}} padding={{horizontal:6}} background={selected===v.vehicleId?"systemOrange":"systemBlue"} clipShape={{type:"rect",cornerRadius:10}} alignment="center" onTapGesture={()=>focusVehicle(v)}><HStack spacing={3}><Image systemName="bus.fill" font="caption2" foregroundStyle="white"/><Text font="caption" fontWeight="bold" foregroundStyle="white">{v.lineNumber||number}</Text></HStack></VStack></Annotation>:null)}</Map>:null}
    {tab==="live"?(live.length?<ScrollView axes="horizontal" padding={{horizontal:12,top:8,bottom:12}}><HStack spacing={8}>{live.map(v=><VStack key={v.vehicleId} spacing={4} padding={10} frame={{width:158,alignment:"trailing"}} background={selected===v.vehicleId?"systemBlue":"systemGray6"} clipShape={{type:"rect",cornerRadius:14}} alignment="trailing" onTapGesture={()=>focusVehicle(v)}><Text font="subheadline" fontWeight="semibold" foregroundStyle={selected===v.vehicleId?"white":"label"}>{v.destination||`Line ${number}`}</Text><Text font="caption" foregroundStyle={selected===v.vehicleId?"white":"secondaryLabel"}>{v.speedKmh!==undefined?`${Math.round(v.speedKmh)} km/h \u00b7 `:""}{v.lastReported?new Date(v.lastReported).toLocaleTimeString("he-IL",{hour:"2-digit",minute:"2-digit"}):""}</Text>{v.nextStopCode?<Text font="caption2" foregroundStyle={selected===v.vehicleId?"white":"tertiaryLabel"}>{H.next}: {v.nextStopCode}</Text>:null}</VStack>)}</HStack></ScrollView>:<Empty title={H.none}/>):null}
    {tab==="stops"?<ScrollView axes="horizontal" padding={{horizontal:12,top:8,bottom:12}}><HStack spacing={8}>{stops.map((s,i)=><VStack key={s.code} spacing={3} padding={9} frame={{width:150,alignment:"trailing"}} background="systemGray6" clipShape={{type:"rect",cornerRadius:12}} alignment="trailing" onTapGesture={()=>focusStop(s)}><Text font="caption2" foregroundStyle="systemBlue">{i+1}</Text><Text font="subheadline" lineLimit={2}>{s.name}</Text><Text font="caption2" foregroundStyle="tertiaryLabel">{s.code}</Text></VStack>)}</HStack></ScrollView>:null}
    {tab==="alerts"?(alerts.length?<VStack padding={12} spacing={8}>{alerts.slice(0,5).map(a=><VStack key={a.id} alignment="trailing" padding={10} background="systemGray6" clipShape={{type:"rect",cornerRadius:12}}><Text font="subheadline" fontWeight="semibold">{a.title}</Text>{a.description?<Text font="caption" foregroundStyle="secondaryLabel" lineLimit={3}>{a.description}</Text>:null}</VStack>)}</VStack>:<Empty title={H.noAlerts}/>):null}
  </VStack>
}
