import { VStack,HStack,Text,ScrollView,Spacer,useState,Button } from "scripting"
import { Line,TransitConfig } from "./types"
import { LineBadge } from "./common"
import { executeRich } from "../scripts/lib/transit"
import { updateRenderSelection } from "../scripts/lib/context"
import LineView from "./line-view"
const H={results:"\u05ea\u05d5\u05e6\u05d0\u05d5\u05ea \u05e7\u05d5",direction:"\u05db\u05d9\u05d5\u05d5\u05df",variant:"\u05d7\u05dc\u05d5\u05e4\u05d4",close:"\u05e1\u05d2\u05d5\u05e8 \u05de\u05e4\u05d4"}
export default function LineCandidatesView({title,lines}:{title?:string;lines:Line[]}){
  const [selected,setSelected]=useState<any|undefined>(undefined)
  const open=async(l:Line)=>{if(!l.routeId)return;const bundle=await executeRich({action:"line_details",routeId:l.routeId,includeLive:true,includeAlerts:false});const c=bundle.renderConfig as TransitConfig|undefined;if(c?.type==="line"){setSelected(c);updateRenderSelection({selectedRoute:{lineNumber:String(c.line.lineNumber||c.line.routeNumber||""),routeId:c.line.routeId,routeCode:c.line.routeCode||c.line.code,direction:c.line.direction,alternative:c.line.alternative,agency:c.line.agency,headsign:c.line.headsign}})}}
  return <VStack spacing={0}><HStack padding={{horizontal:14,vertical:9}}><Text font="headline" fontWeight="bold">{title||H.results}</Text><Spacer/><Text font="caption" foregroundStyle="secondaryLabel">{lines.length}</Text></HStack><ScrollView axes="horizontal" padding={{horizontal:12,bottom:12}}><HStack spacing={8}>{lines.map((l,i)=><VStack key={l.routeId+String(i)} spacing={5} padding={10} frame={{width:190,alignment:"trailing"}} background="systemGray6" clipShape={{type:"rect",cornerRadius:14}} alignment="trailing" onTapGesture={()=>{void open(l)}}><HStack><Spacer/><Text font="caption" lineLimit={1}>{l.agency||""}</Text><LineBadge line={String(l.lineNumber||l.routeNumber||"?")} color={l.color}/></HStack><Text font="subheadline" fontWeight="semibold" lineLimit={2}>{l.headsign||l.routeLongName||l.longName||""}</Text><Text font="caption2" foregroundStyle="secondaryLabel">{H.direction} {l.direction||"?"} \u00b7 {H.variant} {l.alternative||"0"}</Text></VStack>)}</HStack></ScrollView>{selected?.type==="line"?<VStack><HStack padding={{horizontal:12}}><Button title={H.close} action={()=>setSelected(undefined)} buttonStyle="bordered" controlSize="small"/><Spacer/></HStack><LineView {...selected}/></VStack>:null}</VStack>
}
