import { VStack,HStack,Text,Image,Spacer,Circle,Rectangle,ProgressView,useState } from "scripting"
import { TransitRequest } from "../scripts/lib/types"

type LoaderKind="search"|"nearby"|"line-candidates"|"stop-board"|"line"|"schedule"|"segment"|"alerts"|"trip-plan"|"shape"|"raw-cards"|"monitor"|"reminder"|"live"|"generic"
type LoaderSpec={kind:LoaderKind;title:string;subtitle:string}

type MotionEffect="bounce"|"breathePulse"|"pulse"|"rotate"|"rotateClockwise"|"variableColor"|"wiggle"|"wiggleForward"
type PathMotion={fromX?:number;toX?:number;fromY?:number;toY?:number;fromRotation?:number;toRotation?:number;fromScale?:number;toScale?:number;duration?:number;autoreverses?:boolean;delay?:number}
function MotionIcon({name,effect="pulse",color="systemBlue",font="title2",speed=0.8,motion}:{name:string;effect?:MotionEffect;color?:string;font?:any;speed?:number;motion?:PathMotion}){
  const [animationTrigger,setAnimationTrigger]=useState(false)
  const animation=motion?Animation.linear(motion.duration??1.2).delay(motion.delay??0).repeatForever(motion.autoreverses??true):undefined
  return <Image systemName={name} font={font} foregroundStyle={color} symbolRenderingMode="hierarchical"
    offset={motion?{x:animationTrigger?(motion.toX??0):(motion.fromX??0),y:animationTrigger?(motion.toY??0):(motion.fromY??0)}:undefined}
    rotationEffect={motion?(animationTrigger?(motion.toRotation??0):(motion.fromRotation??0)):undefined}
    scaleEffect={motion?(animationTrigger?(motion.toScale??1):(motion.fromScale??1)):undefined}
    animation={motion&&animation?{animation,value:animationTrigger}:undefined}
    onAppear={()=>setAnimationTrigger(true)}
    symbolEffect={{effect,value:animationTrigger,options:{repeat:"continuous",speed}}}/>
}
function Bar({width=76,height=8}:{width?:number;height?:number}){return <Rectangle frame={{width,height}} fill="systemGray5" clipShape={{type:"rect",cornerRadius:height/2}}/>}
function Dot({active=false}:{active?:boolean}){return <Circle frame={{width:active?12:9,height:active?12:9}} fill={active?"systemBlue":"systemGray4"}/>}
function MovingDot({active=false,fromX=0,toX=0,duration=1.8}:{active?:boolean;fromX?:number;toX?:number;duration?:number}){
  const [moving,setMoving]=useState(false)
  return <Circle frame={{width:active?12:9,height:active?12:9}} fill={active?"systemBlue":"systemGray4"} offset={{x:moving?toX:fromX,y:0}} animation={{animation:Animation.linear(duration).repeatForever(true),value:moving}} onAppear={()=>setMoving(true)}/>
}
function Base({title,subtitle,children}:{title:string;subtitle:string;children:any}){
  return <VStack spacing={12} padding={{horizontal:14,vertical:14}} alignment="trailing">
    <VStack spacing={3} alignment="trailing" frame={{maxWidth:"infinity",alignment:"trailing"}}>
      <Text font="headline" fontWeight="semibold">{title}</Text>
      <Text font="caption" foregroundStyle="secondaryLabel">{subtitle}</Text>
    </VStack>
    {children}
  </VStack>
}
function NearbyLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><VStack spacing={10} frame={{maxWidth:"infinity",height:112}} background="systemGray6" clipShape={{type:"rect",cornerRadius:14}} alignment="center"><MotionIcon name="location.circle.fill" effect="breathePulse" font="title" motion={{fromScale:1,toScale:1.08,duration:1.15}}/><HStack spacing={26}><MotionIcon name="mappin.circle.fill" effect="pulse" color="systemOrange" font="body" speed={0.65} motion={{fromY:2,toY:-3,duration:1.1,delay:0.05}}/><MotionIcon name="mappin.circle.fill" effect="pulse" font="body" speed={0.85} motion={{fromY:3,toY:-3,duration:1.25,delay:0.15}}/><MotionIcon name="mappin.circle.fill" effect="pulse" color="systemGreen" font="body" speed={1.05} motion={{fromY:2,toY:-3,duration:1.0,delay:0.25}}/></HStack></VStack><HStack spacing={8}><Bar width={92}/><Bar width={64}/><Bar width={84}/><Spacer/></HStack></Base>}
function SearchLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><HStack spacing={12} frame={{maxWidth:"infinity"}} padding={12} background="systemGray6" clipShape={{type:"rect",cornerRadius:14}}><MotionIcon name="magnifyingglass" effect="bounce" motion={{fromX:-4,toX:10,duration:1.25}}/><VStack spacing={7} alignment="trailing"><Bar width={150}/><Bar width={105} height={6}/></VStack><Spacer/><MotionIcon name="mappin.and.ellipse" effect="breathePulse" color="systemOrange" font="body" motion={{fromScale:1,toScale:1.08,duration:1.15}}/></HStack></Base>}
function LineCandidatesLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><HStack spacing={8} frame={{maxWidth:"infinity"}}><VStack spacing={6} padding={10} frame={{width:108,height:82}} background="systemGray6" clipShape={{type:"rect",cornerRadius:14}}><MotionIcon name="bus.fill" effect="bounce" font="body" motion={{fromX:-7,toX:7,duration:1.0}}/><Bar width={66}/><Bar width={44} height={6}/></VStack><VStack spacing={6} padding={10} frame={{width:108,height:82}} background="systemGray6" clipShape={{type:"rect",cornerRadius:14}}><MotionIcon name="arrow.triangle.branch" effect="variableColor" color="systemOrange" font="body"/><Bar width={62}/><Bar width={50} height={6}/></VStack><VStack spacing={6} padding={10} frame={{width:108,height:82}} background="systemGray6" clipShape={{type:"rect",cornerRadius:14}}><MotionIcon name="bus.fill" effect="bounce" color="systemGreen" font="body" speed={1.05} motion={{fromX:-7,toX:7,duration:1.15}}/><Bar width={70}/><Bar width={48} height={6}/></VStack><Spacer/></HStack></Base>}
function StopBoardLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><HStack spacing={10} frame={{maxWidth:"infinity"}}><MotionIcon name="clock.arrow.circlepath" effect="rotateClockwise" motion={{fromRotation:0,toRotation:360,duration:1.5,autoreverses:false}}/><VStack spacing={6} alignment="trailing"><Bar width={128}/><Bar width={84} height={6}/></VStack><Spacer/><MotionIcon name="bus.fill" effect="wiggleForward" color="systemGreen" font="body" motion={{fromX:0,toX:-18,duration:1.2}}/></HStack><HStack spacing={8} frame={{maxWidth:"infinity"}}>{[0,1,2].map(i=><VStack key={i} spacing={6} padding={9} frame={{width:96,height:64}} background="systemGray6" clipShape={{type:"rect",cornerRadius:12}}><Bar width={i===1?52:64}/><Bar width={38} height={6}/></VStack>)}<Spacer/></HStack></Base>}
function LineLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><VStack spacing={9} frame={{maxWidth:"infinity",height:112}} background="systemGray6" clipShape={{type:"rect",cornerRadius:14}} alignment="center"><HStack spacing={0} frame={{maxWidth:"infinity"}}><Dot active/><Rectangle frame={{height:3,maxWidth:"infinity"}} fill="systemBlue"/><MotionIcon name="bus.fill" effect="wiggleForward" font="body" motion={{fromX:-92,toX:92,duration:2.1,autoreverses:false}}/><Rectangle frame={{height:3,maxWidth:"infinity"}} fill="systemBlue"/><Dot active/></HStack><HStack><Bar width={72}/><Spacer/><MotionIcon name="location.fill" effect="pulse" color="systemOrange" font="caption"/><Bar width={92}/></HStack></VStack></Base>}
function ScheduleLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><HStack spacing={10} frame={{maxWidth:"infinity"}}><MotionIcon name="calendar" effect="breathePulse"/><Bar width={120}/><Spacer/><MotionIcon name="clock.fill" effect="pulse" color="systemGreen" font="body" motion={{fromRotation:0,toRotation:360,duration:2.0,autoreverses:false}}/></HStack><VStack spacing={7} frame={{maxWidth:"infinity"}}>{[0,1,2].map(i=><HStack key={i} spacing={10} padding={{horizontal:10,vertical:8}} background="systemGray6" clipShape={{type:"rect",cornerRadius:10}}><Bar width={42}/><Spacer/><Bar width={96-i*8}/><MotionIcon name="clock" effect="pulse" color="secondaryLabel" font="caption" speed={0.7+i*0.15}/></HStack>)}</VStack></Base>}
function SegmentLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><HStack spacing={8} frame={{maxWidth:"infinity"}}><Dot active/><Rectangle frame={{height:3,width:72}} fill="systemBlue"/><MotionIcon name="bus.fill" effect="wiggleForward" motion={{fromX:-72,toX:72,duration:1.7,autoreverses:false}}/><Rectangle frame={{height:3,width:72}} fill="systemBlue"/><Dot active/><Spacer/><MotionIcon name="stopwatch.fill" effect="pulse" color="systemOrange" motion={{fromRotation:0,toRotation:360,duration:2.4,autoreverses:false}}/></HStack><ProgressView progressViewStyle="linear"/></Base>}
function AlertsLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><HStack spacing={10} frame={{maxWidth:"infinity"}}><MotionIcon name="bell.badge.fill" effect="wiggle" color="systemOrange" motion={{fromRotation:-8,toRotation:8,duration:0.55}}/><VStack spacing={6} alignment="trailing"><Bar width={150}/><Bar width={104} height={6}/></VStack><Spacer/></HStack><VStack spacing={7} frame={{maxWidth:"infinity"}}>{[0,1].map(i=><HStack key={i} padding={9} background="systemGray6" clipShape={{type:"rect",cornerRadius:11}}><MotionIcon name="exclamationmark.triangle.fill" effect="pulse" color="systemOrange" font="caption" speed={0.75+i*0.2}/><Spacer/><Bar width={150-i*18}/></HStack>)}</VStack></Base>}
function TripPlanLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><HStack spacing={8} frame={{maxWidth:"infinity"}}><MotionIcon name="location.fill" effect="pulse" color="systemGreen"/><Rectangle frame={{height:3,width:58}} fill="systemGray4"/><MotionIcon name="figure.walk" effect="bounce" color="secondaryLabel" font="body" motion={{fromX:-24,toX:24,duration:1.3}}/><Rectangle frame={{height:3,width:58}} fill="systemBlue"/><MotionIcon name="bus.fill" effect="wiggleForward" motion={{fromX:-28,toX:28,duration:1.35,autoreverses:false,delay:0.12}}/><Rectangle frame={{height:3,width:58}} fill="systemGray4"/><MotionIcon name="flag.fill" effect="pulse" color="systemOrange" motion={{fromScale:1,toScale:1.08,duration:1.0}}/><Spacer/></HStack><HStack spacing={8} frame={{maxWidth:"infinity"}}><VStack padding={9} frame={{width:118,height:58}} background="systemGray6" clipShape={{type:"rect",cornerRadius:12}}><Bar width={76}/><Bar width={48} height={6}/></VStack><VStack padding={9} frame={{width:118,height:58}} background="systemGray6" clipShape={{type:"rect",cornerRadius:12}}><Bar width={82}/><Bar width={42} height={6}/></VStack><Spacer/></HStack></Base>}
function ShapeLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><VStack spacing={10} frame={{maxWidth:"infinity",height:108}} background="systemGray6" clipShape={{type:"rect",cornerRadius:14}} alignment="center"><MotionIcon name="map.fill" effect="variableColor"/><HStack spacing={0}><Dot active/><Rectangle frame={{width:64,height:3}} fill="systemBlue"/><MovingDot fromX={-64} toX={64} duration={1.8}/><Rectangle frame={{width:64,height:3}} fill="systemBlue"/><Dot active/></HStack></VStack></Base>}
function RawCardsLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><HStack spacing={10} frame={{maxWidth:"infinity"}}><MotionIcon name="square.stack.3d.up.fill" effect="variableColor"/><VStack spacing={6} alignment="trailing"><Bar width={142}/><Bar width={94} height={6}/></VStack><Spacer/></HStack><HStack spacing={8}>{[0,1,2].map(i=><VStack key={i} padding={9} spacing={6} frame={{width:96,height:64}} background="systemGray6" clipShape={{type:"rect",cornerRadius:12}}><Bar width={62-i*4}/><Bar width={44} height={6}/></VStack>)}<Spacer/></HStack></Base>}
function MonitorLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><HStack spacing={10} frame={{maxWidth:"infinity"}}><MotionIcon name="dot.radiowaves.left.and.right" effect="variableColor" color="systemGreen" motion={{fromScale:0.94,toScale:1.08,duration:1.0}}/><VStack spacing={6} alignment="trailing"><Bar width={144}/><Bar width={98} height={6}/></VStack><Spacer/><ProgressView progressViewStyle="circular"/></HStack><ProgressView progressViewStyle="linear"/></Base>}
function EngagementLoader({title,subtitle,kind}:{title:string;subtitle:string;kind:"reminder"|"live"}){return <Base title={title} subtitle={subtitle}><HStack spacing={12} frame={{maxWidth:"infinity"}}><MotionIcon name={kind==="reminder"?"bell.badge.fill":"wave.3.right.circle.fill"} effect={kind==="reminder"?"wiggle":"variableColor"} color={kind==="reminder"?"systemOrange":"systemGreen"} font="title" motion={kind==="reminder"?{fromRotation:-8,toRotation:8,duration:0.55}:{fromScale:0.94,toScale:1.08,duration:1.0}}/><VStack spacing={6} alignment="trailing"><Bar width={148}/><Bar width={108} height={6}/></VStack><Spacer/><ProgressView progressViewStyle="circular"/></HStack></Base>}
function GenericLoader({title,subtitle}:{title:string;subtitle:string}){return <Base title={title} subtitle={subtitle}><HStack spacing={10} frame={{maxWidth:"infinity"}}><MotionIcon name="arrow.triangle.2.circlepath" effect="rotateClockwise" motion={{fromRotation:0,toRotation:360,duration:1.5,autoreverses:false}}/><VStack spacing={6} alignment="trailing"><Bar width={148}/><Bar width={96} height={6}/></VStack><Spacer/><ProgressView progressViewStyle="circular"/></HStack></Base>}

function lineLabel(req:Partial<TransitRequest>){const v=req.lineNumber||req.query;return v?` ${String(v)}`:""}
export function loadingSpecForRequest(req:Partial<TransitRequest>):LoaderSpec{
  const action=req.action
  if(action==="geocode")return {kind:"search",title:"מחפש את המקום",subtitle:"מאתר מיקום מדויק לפני המשך הבקשה"}
  if(action==="search_stops")return {kind:"search",title:"מחפש תחנות",subtitle:"מתאים שמות תחנות ומיקומים לתוצאות"}
  if(action==="nearby_stops")return {kind:"nearby",title:"מאתר תחנות קרובות",subtitle:"בודק מרחקים והגעות חיות סביבך"}
  if(action==="nearby_line")return req.departureMode&&req.departureMode!=="next"?{kind:"schedule",title:`מחפש את לוח קו${lineLabel(req)}`,subtitle:"מאתר את התחנה הקרובה ואת הנסיעות המתאימות"}:{kind:"stop-board",title:`מחפש את קו${lineLabel(req)} לידך`,subtitle:"מאתר תחנה קרובה ומעדכן הגעות בזמן אמת"}
  if(action==="search_lines")return {kind:"line-candidates",title:`מאתר חלופות לקו${lineLabel(req)}`,subtitle:"בודק כיוונים, חלופות ויעדים אפשריים"}
  if(action==="stop_board")return {kind:"stop-board",title:"טוען את לוח התחנה",subtitle:"משלב לוח זמנים עם נתוני הגעה בזמן אמת"}
  if(action==="stop_schedule")return {kind:"schedule",title:"בונה את לוח הזמנים",subtitle:"טוען את נסיעות התחנה לתאריך המבוקש"}
  if(action==="line_details")return {kind:"line",title:`טוען את מסלול קו${lineLabel(req)}`,subtitle:"מחבר תחנות, תוואי ורכבים חיים"}
  if(action==="line_live")return {kind:"line",title:`מעדכן את קו${lineLabel(req)} בזמן אמת`,subtitle:"מאתר רכבים חיים וממקם אותם לאורך המסלול"}
  if(action==="line_schedule")return {kind:"schedule",title:`בונה את לוח קו${lineLabel(req)}`,subtitle:"טוען את הנסיעות בכיוון ובתאריך המבוקשים"}
  if(action==="line_segment")return {kind:"segment",title:"מודד את זמן הנסיעה",subtitle:"משווה זמן אמת, היסטוריה ולוח זמנים בין התחנות"}
  if(action==="alerts")return {kind:"alerts",title:"בודק התראות שירות",subtitle:"מחפש שינויים פעילים שמשפיעים על הקו או התחנה"}
  if(action==="plan_trip")return {kind:"trip-plan",title:"מתכנן את המסלול",subtitle:"משווה חלופות, הליכה, קווים והחלפות"}
  if(action==="shape")return {kind:"shape",title:"טוען את תוואי המסלול",subtitle:"בונה את הגאומטריה שתוצג על המפה"}
  if(action==="stop_pois")return {kind:"raw-cards",title:"מחפש נקודות עניין",subtitle:"טוען מקומות רלוונטיים סביב התחנה"}
  if(action==="stop_validations")return {kind:"raw-cards",title:"טוען נתוני תיקופים",subtitle:"מרכז את רשומות התיקוף של התחנה"}
  if(action==="stop_watch"||action==="line_watch"||action==="alerts_watch"||action==="trip_watch")return {kind:"monitor",title:"מפעיל מעקב",subtitle:"מכין את תנאי הבדיקה והעדכונים האוטומטיים"}
  if(action==="watch_control")return {kind:"monitor",title:"מעדכן את המעקב",subtitle:"מסנכרן את מצב המעקב והפעולה שביקשת"}
  return {kind:"generic",title:"מכין את נתוני התחבורה",subtitle:"מרכז את המידע הדרוש לתצוגה"}
}
export function TransitLoadingView({request}:{request:Partial<TransitRequest>}){const s=loadingSpecForRequest(request);return <LoadingByKind {...s}/>}
export function EngagementLoadingView({kind}:{kind:"reminder"|"live"}){return <EngagementLoader kind={kind} title={kind==="reminder"?"מתזמן תזכורת יציאה":"מפעיל Live Activity"} subtitle={kind==="reminder"?"מחשב את זמן היציאה ושומר את ההתראה":"מחבר את המסלול לעדכונים החיים"}/>}
export function InlineLoadingIndicator({kind="generic",text}:{kind?:LoaderKind;text:string}){
  const icon=kind==="schedule"?"calendar":kind==="line"?"bus.fill":kind==="stop-board"?"clock.arrow.circlepath":kind==="trip-plan"?"arrow.triangle.2.circlepath":kind==="monitor"?"dot.radiowaves.left.and.right":kind==="reminder"?"bell.badge.fill":kind==="live"?"wave.3.right.circle.fill":"arrow.triangle.2.circlepath"
  const effect:MotionEffect=kind==="line"?"wiggleForward":kind==="monitor"||kind==="live"?"variableColor":kind==="reminder"?"wiggle":kind==="schedule"?"breathePulse":"rotateClockwise"
  const motion:PathMotion|undefined=kind==="line"?{fromX:-5,toX:5,duration:0.9}:kind==="schedule"||kind==="stop-board"||kind==="trip-plan"||kind==="generic"?{fromRotation:0,toRotation:360,duration:1.4,autoreverses:false}:kind==="reminder"?{fromRotation:-7,toRotation:7,duration:0.55}:kind==="monitor"||kind==="live"?{fromScale:0.94,toScale:1.08,duration:0.95}:undefined
  return <HStack spacing={6}><MotionIcon name={icon} effect={effect} font="caption" speed={0.85} motion={motion}/><Text font="caption" foregroundStyle="secondaryLabel">{text}</Text></HStack>
}
function LoadingByKind(s:LoaderSpec){switch(s.kind){case "search":return <SearchLoader {...s}/>;case "nearby":return <NearbyLoader {...s}/>;case "line-candidates":return <LineCandidatesLoader {...s}/>;case "stop-board":return <StopBoardLoader {...s}/>;case "line":return <LineLoader {...s}/>;case "schedule":return <ScheduleLoader {...s}/>;case "segment":return <SegmentLoader {...s}/>;case "alerts":return <AlertsLoader {...s}/>;case "trip-plan":return <TripPlanLoader {...s}/>;case "shape":return <ShapeLoader {...s}/>;case "raw-cards":return <RawCardsLoader {...s}/>;case "monitor":return <MonitorLoader {...s}/>;case "reminder":case "live":return <EngagementLoader kind={s.kind} title={s.title} subtitle={s.subtitle}/>;default:return <GenericLoader {...s}/>}}
