import { VStack,HStack,Text,Image,ScrollView,Spacer,Button,useState,useEffect } from "scripting"
import { Stop,Departure,Vehicle,Alert,TransitConfig } from "./types"
import { DepartureCard,LineBadge,Empty } from "./common"
import { formatMinutesHe } from "../scripts/lib/time"
import { realtime, stopSchedule, stopSummary } from "../scripts/lib/kavnav"
import { mergeStopBoard } from "../scripts/lib/normalize"
import { executeRich } from "../scripts/lib/transit"
import { updateRenderSelection } from "../scripts/lib/context"
import LineView from "./line-view"
import { InlineLoadingIndicator } from "./loading-view"
const H={next:"\u05d4\u05d1\u05d0\u05d9\u05dd",routes:"\u05e7\u05d5\u05d5\u05d9\u05dd",nearby:"\u05e1\u05de\u05d5\u05db\u05d5\u05ea",alerts:"\u05d4\u05ea\u05e8\u05d0\u05d5\u05ea",refresh:"\u05e8\u05e2\u05e0\u05df",refreshing:"\u05de\u05e8\u05e2\u05e0\u05df...",noDepartures:"\u05d0\u05d9\u05df \u05d9\u05e6\u05d9\u05d0\u05d5\u05ea \u05e7\u05e8\u05d5\u05d1\u05d5\u05ea",noNearby:"\u05d0\u05d9\u05df \u05ea\u05d7\u05e0\u05d5\u05ea \u05e1\u05de\u05d5\u05db\u05d5\u05ea",noAlerts:"\u05d0\u05d9\u05df \u05d4\u05ea\u05e8\u05d0\u05d5\u05ea \u05e4\u05e2\u05d9\u05dc\u05d5\u05ea",direction:"\u05db\u05d9\u05d5\u05d5\u05df",variant:"\u05d7\u05dc\u05d5\u05e4\u05d4",station:"\u05ea\u05d7\u05e0\u05d4",updated:"\u05e2\u05d5\u05d3\u05db\u05df",lines:"\u05e7\u05d5\u05d5\u05d9\u05dd",walking:"\u05d3\u05e7\u05f3 \u05d4\u05dc\u05d9\u05db\u05d4",close:"\u05e1\u05d2\u05d5\u05e8 \u05de\u05e4\u05ea \u05e7\u05d5"}
export default function StopBoardView({stop,date,routes,departures,vehicles,alerts,lastVehicleReport,neighbors=[],restrictions={},lineFilter,routeIdFilter=[]}:{stop:Stop;date:string;routes:any[];departures:Departure[];vehicles:Vehicle[];alerts:Alert[];lastVehicleReport?:string;neighbors?:any[];restrictions?:any;lineFilter?:string;routeIdFilter?:string[]}){
  const routeSet=new Set((routeIdFilter||[]).map(String))
  const sameLine=(v:any)=>{const id=String(v?.routeId||"");if(routeSet.size)return !!id&&routeSet.has(id);return !lineFilter||String(v?.lineNumber||v?.routeNumber||"")===String(lineFilter)}
  const applyLineFilter=(board:any)=>(lineFilter||routeSet.size)?{...board,departures:(board.departures||[]).filter(sameLine),routes:(board.routes||[]).filter(sameLine),vehicles:(board.vehicles||[]).filter(sameLine)}:board
  const [tab,setTab]=useState("next"),[shownDepartures,setShownDepartures]=useState(departures),[shownRoutes,setShownRoutes]=useState(routes),[shownVehicles,setShownVehicles]=useState(vehicles),[updated,setUpdated]=useState(lastVehicleReport),[refreshing,setRefreshing]=useState(false),[selectedLine,setSelectedLine]=useState<any|undefined>(undefined),[loadingRouteId,setLoadingRouteId]=useState<string|undefined>(undefined)
  const refresh=async()=>{if(refreshing)return;setRefreshing(true);try{const [summary,schedule,rt]=await Promise.all([stopSummary(stop.code),stopSchedule(stop.code,date),realtime({stopCode:stop.code})]);const board=applyLineFilter(mergeStopBoard(stop.code,date,summary,schedule,rt,30));setShownDepartures(board.departures);setShownRoutes(board.routes);setShownVehicles(board.vehicles);setUpdated(rt?.lastVehicleReport)}finally{setRefreshing(false)}}
  useEffect(()=>{let cancelled=false,timer:any;const tick=async()=>{try{const [summary,schedule,rt]=await Promise.all([stopSummary(stop.code),stopSchedule(stop.code,date),realtime({stopCode:stop.code})]);if(!cancelled){const board=applyLineFilter(mergeStopBoard(stop.code,date,summary,schedule,rt,30));setShownDepartures(board.departures);setShownRoutes(board.routes);setShownVehicles(board.vehicles);setUpdated(rt?.lastVehicleReport)}}catch{}if(!cancelled)timer=setTimeout(tick,20000)};timer=setTimeout(tick,20000);return()=>{cancelled=true;if(timer)clearTimeout(timer)}},[])
  const openRoute=async(r:any)=>{if(!r?.routeId||loadingRouteId)return;setLoadingRouteId(String(r.routeId));try{const bundle=await executeRich({action:"line_details",routeId:String(r.routeId),includeLive:true,includeAlerts:false});const c=bundle.renderConfig as TransitConfig|undefined;if(c?.type==="line"){setSelectedLine(c);updateRenderSelection({selectedRoute:{lineNumber:String(c.line.lineNumber||c.line.routeNumber||r.routeNumber||""),routeId:c.line.routeId,routeCode:c.line.routeCode||c.line.code,direction:c.line.direction,alternative:c.line.alternative,agency:c.line.agency,headsign:c.line.headsign}})}}finally{setLoadingRouteId(undefined)}}
  const restrictionText=Object.entries(restrictions||{}).filter(([,v])=>Array.isArray(v)&&v.length).map(([k,v])=>`${k}: ${(v as any[]).length}`).join(" \u00b7 ")
  return <VStack spacing={0}>
    <HStack padding={{horizontal:14,top:10,bottom:6}}><VStack alignment="trailing" spacing={2}><Text font="headline" fontWeight="bold">{stop.name}{lineFilter?` · קו ${lineFilter}`:""}</Text><Text font="caption" foregroundStyle="secondaryLabel">{H.station} {stop.code}{updated?` \u00b7 ${H.updated} ${new Date(updated).toLocaleTimeString("he-IL",{hour:"2-digit",minute:"2-digit"})}`:""}</Text></VStack><Spacer/>{refreshing?<InlineLoadingIndicator kind="stop-board" text="מעדכן הגעות בזמן אמת"/>:null}<Button title={refreshing?H.refreshing:H.refresh} action={()=>{void refresh()}} buttonStyle="bordered" controlSize="small"/></HStack>
    <ScrollView axes="horizontal" padding={{horizontal:12,vertical:6}}><HStack spacing={6}>{[["next",H.next],["routes",H.routes],["nearby",H.nearby],["alerts",H.alerts]].map(([id,t])=><Button key={id} title={t} action={()=>setTab(id)} buttonStyle={tab===id?"borderedProminent":"bordered"} controlSize="small"/>)}</HStack></ScrollView>
    {tab==="next"?(shownDepartures.length?<ScrollView axes="horizontal" padding={{horizontal:12,top:6,bottom:12}}><HStack spacing={8}>{shownDepartures.map((d,i)=><DepartureCard key={d.tripId||String(i)} d={d} compact={!!lineFilter||routeSet.size>0}/>)}</HStack></ScrollView>:<Empty title={H.noDepartures}/>):null}
    {tab==="routes"?<VStack spacing={6}>{restrictionText?<Text padding={{horizontal:14}} font="caption2" foregroundStyle="secondaryLabel">{restrictionText}</Text>:null}<ScrollView axes="horizontal" padding={{horizontal:12,top:6,bottom:12}}><HStack spacing={8}>{shownRoutes.slice(0,30).map((r:any)=><VStack key={r.routeId} spacing={5} padding={10} frame={{width:160,alignment:"trailing"}} background="systemGray6" clipShape={{type:"rect",cornerRadius:14}} alignment="trailing" onTapGesture={()=>{void openRoute(r)}}><HStack><Spacer/><Text font="caption" foregroundStyle="secondaryLabel" lineLimit={1}>{r.headsign||""}</Text><LineBadge line={String(r.routeNumber||"?")} color={r.color||undefined}/></HStack><Text font="caption2" foregroundStyle="tertiaryLabel">{H.direction} {r.direction||"?"} \u00b7 {H.variant} {r.alternative||"0"}</Text></VStack>)}</HStack></ScrollView>{loadingRouteId?<HStack padding={{horizontal:14,bottom:6}}><InlineLoadingIndicator kind="line" text="טוען את מסלול הקו שבחרת"/><Spacer/></HStack>:null}{selectedLine?.type==="line"?<VStack spacing={6}><HStack padding={{horizontal:12}}><Button title={H.close} action={()=>setSelectedLine(undefined)} buttonStyle="bordered" controlSize="small"/><Spacer/></HStack><LineView {...selectedLine}/></VStack>:null}</VStack>:null}
    {tab==="nearby"?(neighbors.length?<ScrollView axes="horizontal" padding={{horizontal:12,top:6,bottom:12}}><HStack spacing={8}>{neighbors.slice(0,20).map((n:any,i:number)=><VStack key={String(n.stopCode||i)} spacing={4} padding={10} frame={{width:145,alignment:"trailing"}} background="systemGray6" clipShape={{type:"rect",cornerRadius:12}} alignment="trailing"><HStack><Spacer/><Image systemName="figure.walk" foregroundStyle="systemBlue"/><Text font="subheadline" fontWeight="semibold">{n.stopCode||H.station}</Text></HStack>{n.walkingDistanceMeters!==undefined?<Text font="caption" foregroundStyle="secondaryLabel">{Math.round(n.walkingDistanceMeters)} m \u00b7 {formatMinutesHe(Math.round((n.walkingDurationSeconds||0)/60),"0 דק׳")}</Text>:null}<Text font="caption2" foregroundStyle="tertiaryLabel">{Array.isArray(n.routeIds)?`${n.routeIds.length} ${H.lines}`:""}</Text></VStack>)}</HStack></ScrollView>:<Empty title={H.noNearby}/>):null}
    {tab==="alerts"?(alerts.length?<VStack spacing={8} padding={12}>{alerts.slice(0,4).map(a=><VStack key={a.id} spacing={4} padding={10} background="systemGray6" clipShape={{type:"rect",cornerRadius:12}} alignment="trailing"><HStack><Spacer/><Image systemName="exclamationmark.triangle.fill" foregroundStyle="systemOrange"/></HStack><Text font="subheadline" fontWeight="semibold">{a.title}</Text>{a.description?<Text font="caption" foregroundStyle="secondaryLabel" lineLimit={3}>{a.description}</Text>:null}</VStack>)}</VStack>:<Empty title={H.noAlerts}/>):null}
  </VStack>
}
