import { Map,Marker,Annotation,MapPolyline,useObservable,useState,useEffect,VStack,HStack,Text,Image,ScrollView,Spacer,Button,Circle,Rectangle } from "scripting"
import { Coordinate,Itinerary,Leg,TransitConfig } from "./types"
import { executeRich } from "../scripts/lib/transit"
import { updateRenderSelection } from "../scripts/lib/context"
import { realtime } from "../scripts/lib/kavnav"
import { normalizeVehicles } from "../scripts/lib/normalize"
import { formatMinutesHe } from "../scripts/lib/time"
import { saveTripEngagementContext, scheduleTripReminder, startTripLiveActivity } from "../scripts/lib/trip-engagement"
const H={remind:"\u05d4\u05d6\u05db\u05e8 \u05dc\u05d9 \u05dc\u05e6\u05d0\u05ea",live:"Live Activity",scheduled:"\u05d4\u05d4\u05ea\u05e8\u05d0\u05d4 \u05ea\u05d5\u05d6\u05de\u05e0\u05d4",liveStarted:"Live Activity \u05d4\u05d5\u05e4\u05e2\u05dc\u05d4",actionFailed:"\u05dc\u05d0 \u05e0\u05d9\u05ea\u05df \u05dc\u05d4\u05e9\u05dc\u05d9\u05dd \u05d0\u05ea \u05d4\u05e4\u05e2\u05d5\u05dc\u05d4",fast:"\u05d4\u05db\u05d9 \u05de\u05d4\u05d9\u05e8",option:"\u05d0\u05e4\u05e9\u05e8\u05d5\u05ea",walk:"\u05d4\u05dc\u05d9\u05db\u05d4",line:"\u05e7\u05d5",board:"\u05e2\u05dc\u05d9\u05d9\u05d4",alight:"\u05d9\u05e8\u05d9\u05d3\u05d4",transfer:"\u05d4\u05d7\u05dc\u05e4\u05d4",stops:"\u05ea\u05d7\u05e0\u05d5\u05ea",min:"\u05d3\u05e7\u05f3",fullLine:"\u05d4\u05e6\u05d2 \u05e7\u05d5 \u05de\u05dc\u05d0",backTrip:"\u05d7\u05d6\u05e8\u05d4 \u05dc\u05de\u05e1\u05dc\u05d5\u05dc",loading:"\u05d8\u05d5\u05e2\u05df \u05e7\u05d5...",noRoutes:"\u05dc\u05d0 \u05e0\u05de\u05e6\u05d0\u05d5 \u05de\u05e1\u05dc\u05d5\u05dc\u05d9\u05dd"}
const clock=(ms?:number)=>ms?new Date(ms).toLocaleTimeString("he-IL",{hour:"2-digit",minute:"2-digit"}):"",mins=(s=0)=>Math.max(0,Math.round(s/60)),legCoords=(l?:Leg)=>l?.coordinates||[]
function modeIcon(mode:string){return mode==="WALK"?"figure.walk":mode==="RAIL"||mode==="TRAIN"?"tram.fill":"bus.fill"}
function fit(camera:any,coords:Coordinate[],fallback:any){if(coords.length)camera.setValue(MapCameraPosition.region(MapUtils.regionFromCoordinates(coords,0.24)||fallback))}
export default function TripPlanView({from,to,itineraries,height=260}:{from:any;to:any;itineraries:Itinerary[];height?:number}){
  const [selected,setSelected]=useState(0),[selectedLeg,setSelectedLeg]=useState<number|undefined>(undefined),[overlay,setOverlay]=useState<any|undefined>(undefined),[loadingLine,setLoadingLine]=useState(false),[engagementBusy,setEngagementBusy]=useState<"reminder"|"live"|undefined>(undefined),[engagementStatus,setEngagementStatus]=useState<string|undefined>(undefined)
  const it=itineraries[selected]||itineraries[0]
  if(!it)return <VStack padding={20}><Text>{H.noRoutes}</Text></VStack>
  const coords=it.legs.flatMap(l=>legCoords(l)),endpoints:Coordinate[]=[from?.lat!==undefined?{latitude:from.lat,longitude:from.lon}:undefined,to?.lat!==undefined?{latitude:to.lat,longitude:to.lon}:undefined].filter(Boolean) as Coordinate[]
  const baseRegion=MapUtils.regionFromCoordinates(coords.length?coords:endpoints,0.22)||{center:{latitude:31.78,longitude:35.22},span:{latitudeDelta:.05,longitudeDelta:.05}},camera=useObservable(MapCameraPosition.region(baseRegion))
  const choose=(i:number)=>{setSelected(i);setSelectedLeg(undefined);setOverlay(undefined);updateRenderSelection({selectedItinerary:i,selectedLeg:undefined,selectedRoute:undefined});const chosen=itineraries[i];if(chosen)saveTripEngagementContext({fromName:String(from?.name||from?.orig||"Start"),toName:String(to?.name||to?.orig||"End"),itinerary:chosen});fit(camera,chosen?.legs.flatMap(l=>legCoords(l))||[],baseRegion)}
  const selectLeg=(i:number)=>{setSelectedLeg(i);setOverlay(undefined);updateRenderSelection({selectedItinerary:selected,selectedLeg:i,selectedRoute:undefined});fit(camera,legCoords(it.legs[i]),baseRegion)}
  const openLine=async(i:number)=>{const leg=it.legs[i];if(!leg?.routeId||loadingLine)return;setLoadingLine(true);try{const bundle=await executeRich({action:"line_details",routeId:leg.routeId,includeLive:true,includeAlerts:false});const c=bundle.renderConfig as TransitConfig|undefined;if(c?.type==="line"){setOverlay(c);setSelectedLeg(i);updateRenderSelection({selectedItinerary:selected,selectedLeg:i,selectedRoute:{lineNumber:String(c.line.lineNumber||c.line.routeNumber||leg.route||""),routeId:c.line.routeId,routeCode:c.line.routeCode||c.line.code,direction:c.line.direction,alternative:c.line.alternative,agency:c.line.agency,headsign:c.line.headsign}});fit(camera,c.coordinates,baseRegion)}}finally{setLoadingLine(false)}}
  const fromName=String(from?.name||from?.orig||"Start"),toName=String(to?.name||to?.orig||"End")
  useEffect(()=>{saveTripEngagementContext({fromName,toName,itinerary:it})},[selected,it.startTime,it.endTime])
  const remind=async()=>{if(engagementBusy)return;setEngagementBusy("reminder");setEngagementStatus(undefined);try{const r=await scheduleTripReminder({fromName,toName,itinerary:it});setEngagementStatus(r.ok?H.scheduled:(r.message||H.actionFailed))}catch(e){setEngagementStatus(e instanceof Error?e.message:String(e))}finally{setEngagementBusy(undefined)}}
  const startLive=async()=>{if(engagementBusy)return;setEngagementBusy("live");setEngagementStatus(undefined);try{const r=await startTripLiveActivity({fromName,toName,itinerary:it});setEngagementStatus(r.ok?H.liveStarted:(r.message||H.actionFailed))}catch(e){setEngagementStatus(e instanceof Error?e.message:String(e))}finally{setEngagementBusy(undefined)}}
  const now=Date.now(),showReminder=it.startTime>now+60*1000,showLive=it.startTime<=now+10*60*1000&&it.endTime>now-10*60*1000
  useEffect(()=>{if(overlay?.type!=="line")return;const current=overlay,routeCode=String(current.line.routeCode||current.line.code||""),routeId=String(current.line.routeId||"");if(!routeCode)return;let cancelled=false,timer:any;const tick=async()=>{try{const raw=await realtime({routeCode});if(!cancelled){const vehicles=normalizeVehicles(raw).filter(v=>!routeId||v.routeId===routeId);setOverlay({...current,vehicles,lastVehicleReport:raw?.lastVehicleReport})}}catch{}if(!cancelled)timer=setTimeout(tick,15000)};timer=setTimeout(tick,15000);return()=>{cancelled=true;if(timer)clearTimeout(timer)}},[overlay?.line?.routeId])
  return <VStack spacing={0}>
    <HStack padding={{horizontal:14,vertical:8}}><VStack alignment="trailing"><Text font="headline" fontWeight="bold" lineLimit={1}>{from?.name||from?.orig||"Start"} &#8592; {to?.name||to?.orig||"End"}</Text><Text font="caption" foregroundStyle="secondaryLabel">{clock(it.startTime)}&#8211;{clock(it.endTime)} &#183; {formatMinutesHe(mins(it.durationSeconds),"0 דק׳")} &#183; {it.transfers||0} {H.transfer}</Text></VStack><Spacer/><Image systemName="point.topleft.down.to.point.bottomright.curvepath" foregroundStyle="systemBlue"/></HStack>
    {(showReminder||showLive)?<VStack spacing={6} padding={{horizontal:14,bottom:8}}><HStack spacing={8}>{showReminder?<Button title={engagementBusy==="reminder"?H.loading:H.remind} action={()=>{void remind()}} disabled={!!engagementBusy} buttonStyle="borderedProminent" controlSize="small"/>:null}{showLive?<Button title={engagementBusy==="live"?H.loading:H.live} action={()=>{void startLive()}} disabled={!!engagementBusy} buttonStyle="bordered" controlSize="small"/>:null}<Spacer/></HStack>{engagementStatus?<Text font="caption2" foregroundStyle="secondaryLabel">{engagementStatus}</Text>:null}</VStack>:null}
    <Map cameraPosition={camera} frame={{height}} mapStyle={{style:"standard"}} clipShape={{type:"rect",cornerRadius:14}}>{from?.lat!==undefined&&!overlay?<Marker coordinate={{latitude:from.lat,longitude:from.lon}} title={from.name||"Start"} tint="systemGreen" systemImage="location.fill"/>:null}{to?.lat!==undefined&&!overlay?<Marker coordinate={{latitude:to.lat,longitude:to.lon}} title={to.name||"End"} tint="systemRed" systemImage="flag.fill"/>:null}{overlay?.type==="line"?<MapPolyline coordinates={overlay.coordinates} strokeColor={overlay.line.color||"systemBlue"} strokeStyle={{lineWidth:6,lineCap:"round",lineJoin:"round"}}/>:it.legs.map((l,i)=>legCoords(l).length>1?<MapPolyline key={i} coordinates={legCoords(l)} strokeColor={l.mode==="WALK"?"secondaryLabel":l.color||"systemBlue"} strokeStyle={{lineWidth:selectedLeg===i?7:l.mode==="WALK"?3:5,dash:l.mode==="WALK"?[5,5]:undefined,lineCap:"round",lineJoin:"round"}}/>:null)}{!overlay?it.legs.flatMap((l,i)=>l.mode==="WALK"?[]:[l.from.coordinate?<Marker key={`b${i}`} coordinate={l.from.coordinate} title={`${H.board} ${H.line} ${l.route||""}`} tint="systemGreen" systemImage="arrow.up.circle.fill"/>:null,l.to.coordinate?<Marker key={`a${i}`} coordinate={l.to.coordinate} title={H.alight} tint="systemOrange" systemImage="arrow.down.circle.fill"/>:null]):null}{overlay?.type==="line"?(overlay.vehicles||[]).map((v:any)=>v.coordinate?<Annotation key={v.vehicleId} coordinate={v.coordinate} title={String(overlay.line.lineNumber||"")} anchor="center"><HStack spacing={3} padding={{horizontal:7,vertical:5}} background="systemBlue" clipShape={{type:"rect",cornerRadius:10}}><Image systemName="bus.fill" font="caption2" foregroundStyle="white"/><Text font="caption" fontWeight="bold" foregroundStyle="white">{overlay.line.lineNumber||""}</Text></HStack></Annotation>:null):null}</Map>
    {overlay?.type==="line"?<HStack padding={{horizontal:12,top:8}}><Button title={H.backTrip} action={()=>{setOverlay(undefined);fit(camera,coords,baseRegion)}} buttonStyle="bordered" controlSize="small"/><Spacer/><Text font="subheadline" fontWeight="semibold">{H.line} {overlay.line.lineNumber||overlay.line.routeNumber||""}</Text></HStack>:null}
    <ScrollView axes="horizontal" padding={{horizontal:12,top:9,bottom:8}}><HStack spacing={8}>{itineraries.map((x,i)=><VStack key={i} spacing={4} padding={10} frame={{width:125}} background={selected===i?"systemBlue":"systemGray6"} clipShape={{type:"rect",cornerRadius:14}} onTapGesture={()=>choose(i)}><Text font="caption" foregroundStyle={selected===i?"white":"secondaryLabel"}>{i===0?H.fast:`${H.option} ${i+1}`}</Text><Text font="title3" fontWeight="bold" foregroundStyle={selected===i?"white":"label"}>{formatMinutesHe(mins(x.durationSeconds),"0 דק׳")}</Text><Text font="caption2" foregroundStyle={selected===i?"white":"tertiaryLabel"}>{x.legs.filter(l=>l.mode!=="WALK").map(l=>l.route).filter(Boolean).join(" \u2192 ")||H.walk}</Text>{x.fare?<Text font="caption2" foregroundStyle={selected===i?"white":"tertiaryLabel"}>{x.fare.symbol||"ILS"}{x.fare.amount.toFixed(1)}</Text>:null}</VStack>)}</HStack></ScrollView>
    <VStack spacing={0} padding={{horizontal:12,bottom:14}}>{it.legs.map((l,i)=>{const walk=l.mode==="WALK",last=i===it.legs.length-1,transfer=i>0&&!walk,stopCount=(l.intermediateStops?.length||0)+(walk?0:2);return <HStack key={i} spacing={10} alignment="top" padding={{vertical:3}} onTapGesture={()=>selectLeg(i)}><VStack frame={{width:26}} spacing={2} alignment="center"><Circle frame={{width:selectedLeg===i?14:11,height:selectedLeg===i?14:11}} fill={walk?"secondaryLabel":l.color||"systemBlue"}/>{!last?(walk?<Text font="title2" foregroundStyle="secondaryLabel">&#9478;</Text>:<Rectangle frame={{width:3,height:58}} fill={l.color||"systemBlue"}/>):null}</VStack><VStack spacing={4} alignment="trailing" padding={9} background={selectedLeg===i?"systemGray5":"systemGray6"} clipShape={{type:"rect",cornerRadius:12}}><HStack><Image systemName={modeIcon(l.mode)} foregroundStyle={walk?"secondaryLabel":l.color||"systemBlue"}/><Text font="subheadline" fontWeight="semibold">{walk?H.walk:`${H.line} ${l.route||""}`}</Text><Spacer/><Text font="caption" foregroundStyle="secondaryLabel">{clock(l.startTime)} &#183; {formatMinutesHe(mins(l.durationSeconds),"0 דק׳")}</Text></HStack><Text font="caption" lineLimit={2}>{l.from.name} &#8592; {l.to.name}</Text>{transfer?<Text font="caption2" foregroundStyle="systemOrange">{H.transfer}</Text>:null}<HStack><Text font="caption2" foregroundStyle="tertiaryLabel">{walk?`${Math.round(l.distanceMeters||0)} m`: `${H.board}: ${l.from.name} &#183; ${H.alight}: ${l.to.name}${stopCount?` &#183; ${stopCount} ${H.stops}`:""}`}</Text><Spacer/>{!walk&&l.routeId?<Button title={loadingLine&&selectedLeg===i?H.loading:H.fullLine} action={()=>{void openLine(i)}} buttonStyle="bordered" controlSize="small"/>:null}</HStack></VStack></HStack>})}</VStack>
  </VStack>
}
